import { Component } from '@angular/core';
import { NavParams, ViewController, } from 'ionic-angular';
import { CountryPickerService } from 'angular2-countrypicker';

import { CommonService } from '../../services/common.service';

@Component({
  selector: 'page-country-list-pop',
  template:`<ion-item *ngFor="let c of countries" (click)="countrySelected(c)">
    <span class="{{'flag-icon flag-icon-' + c[1] }}" width="16" height="16" item-left></span>
    <ion-label>{{c[0] }}</ion-label>
  </ion-item>`


})
export class CountryListPopPage {

  public countries: any[] = [{"name":"Aruba","cca3":"abw"},
{"name":"Afghanistan","cca3":"afg"},
{"name":"Angola","cca3":"ago"},
{"name":"Anguilla","cca3":"aia"},
{"name":"\u00c5land Islands","cca3":"ala"},
{"name":"Albania","cca3":"alb"},
{"name":"Andorra","cca3":"and"},
{"name":"United Arab Emirates","cca3":"are"},
{"name":"Argentina","cca3":"arg"},
{"name":"Armenia","cca3":"arm"},
{"name":"American Samoa","cca3":"asm"},
{"name":"Antarctica","cca3":"ata"},
{"name":"French Southern and Antarctic Lands","cca3":"atf"},
{"name":"Antigua and Barbuda","cca3":"atg"},
{"name":"Australia","cca3":"aus"},
{"name":"Austria","cca3":"aut"},
{"name":"Azerbaijan","cca3":"aze"},
{"name":"Burundi","cca3":"bdi"},
{"name":"Belgium","cca3":"bel"},
{"name":"Benin","cca3":"ben"},
{"name":"Burkina Faso","cca3":"bfa"},
{"name":"Bangladesh","cca3":"bgd"},
{"name":"Bulgaria","cca3":"bgr"},
{"name":"Bahrain","cca3":"bhr"},
{"name":"Bahamas","cca3":"bhs"},
{"name":"Bosnia and Herzegovina","cca3":"bih"},
{"name":"Saint Barth\u00e9lemy","cca3":"blm"},
{"name":"Belarus","cca3":"blr"},
{"name":"Belize","cca3":"blz"},
{"name":"Bermuda","cca3":"bmu"},
{"name":"Bolivia","cca3":"bol"},
{"name":"Brazil","cca3":"bra"},
{"name":"Barbados","cca3":"brb"},
{"name":"Brunei","cca3":"brn"},
{"name":"Bhutan","cca3":"btn"},
{"name":"Bouvet Island","cca3":"bvt"},
{"name":"Botswana","cca3":"bwa"},
{"name":"Central African Republic","cca3":"caf"},
{"name":"Canada","cca3":"can"},
{"name":"Cocos (Keeling) Islands","cca3":"cck"},
{"name":"Switzerland","cca3":"che"},
{"name":"Chile","cca3":"chl"},
{"name":"China","cca3":"chn"},
{"name":"Ivory Coast","cca3":"civ"},
{"name":"Cameroon","cca3":"cmr"},
{"name":"DR Congo","cca3":"cod"},
{"name":"Republic of the Congo","cca3":"cog"},
{"name":"Cook Islands","cca3":"cok"},
{"name":"Colombia","cca3":"col"},
{"name":"Comoros","cca3":"com"},
{"name":"Cape Verde","cca3":"cpv"},
{"name":"Costa Rica","cca3":"cri"},
{"name":"Cuba","cca3":"cub"},
{"name":"Cura\u00e7ao","cca3":"cuw"},
{"name":"Christmas Island","cca3":"cxr"},
{"name":"Cayman Islands","cca3":"cym"},
{"name":"Cyprus","cca3":"cyp"},
{"name":"Czechia","cca3":"cze"},
{"name":"Germany","cca3":"deu"},
{"name":"Djibouti","cca3":"dji"},
{"name":"Dominica","cca3":"dma"},
{"name":"Denmark","cca3":"dnk"},
{"name":"Dominican Republic","cca3":"dom"},
{"name":"Algeria","cca3":"dza"},
{"name":"Ecuador","cca3":"ecu"},
{"name":"Egypt","cca3":"egy"},
{"name":"Eritrea","cca3":"eri"},
{"name":"Western Sahara","cca3":"esh"},
{"name":"Spain","cca3":"esp"},
{"name":"Estonia","cca3":"est"},
{"name":"Ethiopia","cca3":"eth"},
{"name":"Finland","cca3":"fin"},
{"name":"Fiji","cca3":"fji"},
{"name":"Falkland Islands","cca3":"flk"},
{"name":"France","cca3":"fra"},
{"name":"Faroe Islands","cca3":"fro"},
{"name":"Micronesia","cca3":"fsm"},
{"name":"Gabon","cca3":"gab"},
{"name":"United Kingdom","cca3":"gbr"},
{"name":"Georgia","cca3":"geo"},
{"name":"Guernsey","cca3":"ggy"},
{"name":"Ghana","cca3":"gha"},
{"name":"Gibraltar","cca3":"gib"},
{"name":"Guinea","cca3":"gin"},
{"name":"Guadeloupe","cca3":"glp"},
{"name":"Gambia","cca3":"gmb"},
{"name":"Guinea-Bissau","cca3":"gnb"},
{"name":"Equatorial Guinea","cca3":"gnq"},
{"name":"Greece","cca3":"grc"},
{"name":"Grenada","cca3":"grd"},
{"name":"Greenland","cca3":"grl"},
{"name":"Guatemala","cca3":"gtm"},
{"name":"French Guiana","cca3":"guf"},
{"name":"Guam","cca3":"gum"},
{"name":"Guyana","cca3":"guy"},
{"name":"Hong Kong","cca3":"hkg"},
{"name":"Heard Island and McDonald Islands","cca3":"hmd"},
{"name":"Honduras","cca3":"hnd"},
{"name":"Croatia","cca3":"hrv"},
{"name":"Haiti","cca3":"hti"},
{"name":"Hungary","cca3":"hun"},
{"name":"Indonesia","cca3":"idn"},
{"name":"Isle of Man","cca3":"imn"},
{"name":"India","cca3":"ind"},
{"name":"British Indian Ocean Territory","cca3":"iot"},
{"name":"Ireland","cca3":"irl"},
{"name":"Iran","cca3":"irn"},
{"name":"Iraq","cca3":"irq"},
{"name":"Iceland","cca3":"isl"},
{"name":"Israel","cca3":"isr"},
{"name":"Italy","cca3":"ita"},
{"name":"Jamaica","cca3":"jam"},
{"name":"Jersey","cca3":"jey"},
{"name":"Jordan","cca3":"jor"},
{"name":"Japan","cca3":"jpn"},
{"name":"Kazakhstan","cca3":"kaz"},
{"name":"Kenya","cca3":"ken"},
{"name":"Kyrgyzstan","cca3":"kgz"},
{"name":"Cambodia","cca3":"khm"},
{"name":"Kiribati","cca3":"kir"},
{"name":"Saint Kitts and Nevis","cca3":"kna"},
{"name":"South Korea","cca3":"kor"},
{"name":"Kosovo","cca3":"unk"},
{"name":"Kuwait","cca3":"kwt"},
{"name":"Laos","cca3":"lao"},
{"name":"Lebanon","cca3":"lbn"},
{"name":"Liberia","cca3":"lbr"},
{"name":"Libya","cca3":"lby"},
{"name":"Saint Lucia","cca3":"lca"},
{"name":"Liechtenstein","cca3":"lie"},
{"name":"Sri Lanka","cca3":"lka"},
{"name":"Lesotho","cca3":"lso"},
{"name":"Lithuania","cca3":"ltu"},
{"name":"Luxembourg","cca3":"lux"},
{"name":"Latvia","cca3":"lva"},
{"name":"Macau","cca3":"mac"},
{"name":"Saint Martin","cca3":"maf"},
{"name":"Morocco","cca3":"mar"},
{"name":"Monaco","cca3":"mco"},
{"name":"Moldova","cca3":"mda"},
{"name":"Madagascar","cca3":"mdg"},
{"name":"Maldives","cca3":"mdv"},
{"name":"Mexico","cca3":"mex"},
{"name":"Marshall Islands","cca3":"mhl"},
{"name":"Macedonia","cca3":"mkd"},
{"name":"Mali","cca3":"mli"},
{"name":"Malta","cca3":"mlt"},
{"name":"Myanmar","cca3":"mmr"},
{"name":"Montenegro","cca3":"mne"},
{"name":"Mongolia","cca3":"mng"},
{"name":"Northern Mariana Islands","cca3":"mnp"},
{"name":"Mozambique","cca3":"moz"},
{"name":"Mauritania","cca3":"mrt"},
{"name":"Montserrat","cca3":"msr"},
{"name":"Martinique","cca3":"mtq"},
{"name":"Mauritius","cca3":"mus"},
{"name":"Malawi","cca3":"mwi"},
{"name":"Malaysia","cca3":"mys"},
{"name":"Mayotte","cca3":"myt"},
{"name":"Namibia","cca3":"nam"},
{"name":"New Caledonia","cca3":"ncl"},
{"name":"Niger","cca3":"ner"},
{"name":"Norfolk Island","cca3":"nfk"},
{"name":"Nigeria","cca3":"nga"},
{"name":"Nicaragua","cca3":"nic"},
{"name":"Niue","cca3":"niu"},
{"name":"Netherlands","cca3":"nld"},
{"name":"Norway","cca3":"nor"},
{"name":"Nepal","cca3":"npl"},
{"name":"Nauru","cca3":"nru"},
{"name":"New Zealand","cca3":"nzl"},
{"name":"Oman","cca3":"omn"},
{"name":"Pakistan","cca3":"pak"},
{"name":"Panama","cca3":"pan"},
{"name":"Pitcairn Islands","cca3":"pcn"},
{"name":"Peru","cca3":"per"},
{"name":"Philippines","cca3":"phl"},
{"name":"Palau","cca3":"plw"},
{"name":"Papua New Guinea","cca3":"png"},
{"name":"Poland","cca3":"pol"},
{"name":"Puerto Rico","cca3":"pri"},
{"name":"North Korea","cca3":"prk"},
{"name":"Portugal","cca3":"prt"},
{"name":"Paraguay","cca3":"pry"},
{"name":"Palestine","cca3":"pse"},
{"name":"French Polynesia","cca3":"pyf"},
{"name":"Qatar","cca3":"qat"},
{"name":"R\u00e9union","cca3":"reu"},
{"name":"Romania","cca3":"rou"},
{"name":"Russia","cca3":"rus"},
{"name":"Rwanda","cca3":"rwa"},
{"name":"Saudi Arabia","cca3":"sau"},
{"name":"Sudan","cca3":"sdn"},
{"name":"Senegal","cca3":"sen"},
{"name":"Singapore","cca3":"sgp"},
{"name":"South Georgia","cca3":"sgs"},
{"name":"Svalbard and Jan Mayen","cca3":"sjm"},
{"name":"Solomon Islands","cca3":"slb"},
{"name":"Sierra Leone","cca3":"sle"},
{"name":"El Salvador","cca3":"slv"},
{"name":"San Marino","cca3":"smr"},
{"name":"Somalia","cca3":"som"},
{"name":"Saint Pierre and Miquelon","cca3":"spm"},
{"name":"Serbia","cca3":"srb"},
{"name":"South Sudan","cca3":"ssd"},
{"name":"S\u00e3o Tom\u00e9 and Pr\u00edncipe","cca3":"stp"},
{"name":"Suriname","cca3":"sur"},
{"name":"Slovakia","cca3":"svk"},
{"name":"Slovenia","cca3":"svn"},
{"name":"Sweden","cca3":"swe"},
{"name":"Swaziland","cca3":"swz"},
{"name":"Sint Maarten","cca3":"sxm"},
{"name":"Seychelles","cca3":"syc"},
{"name":"Syria","cca3":"syr"},
{"name":"Turks and Caicos Islands","cca3":"tca"},
{"name":"Chad","cca3":"tcd"},
{"name":"Togo","cca3":"tgo"},
{"name":"Thailand","cca3":"tha"},
{"name":"Tajikistan","cca3":"tjk"},
{"name":"Tokelau","cca3":"tkl"},
{"name":"Turkmenistan","cca3":"tkm"},
{"name":"Timor-Leste","cca3":"tls"},
{"name":"Tonga","cca3":"ton"},
{"name":"Trinidad and Tobago","cca3":"tto"},
{"name":"Tunisia","cca3":"tun"},
{"name":"Turkey","cca3":"tur"},
{"name":"Tuvalu","cca3":"tuv"},
{"name":"Taiwan","cca3":"twn"},
{"name":"Tanzania","cca3":"tza"},
{"name":"Uganda","cca3":"uga"},
{"name":"Ukraine","cca3":"ukr"},
{"name":"United States Minor Outlying Islands","cca3":"umi"},
{"name":"Uruguay","cca3":"ury"},
{"name":"United States","cca3":"usa"},
{"name":"Uzbekistan","cca3":"uzb"},
{"name":"Vatican City","cca3":"vat"},
{"name":"Saint Vincent and the Grenadines","cca3":"vct"},
{"name":"Venezuela","cca3":"ven"},
{"name":"British Virgin Islands","cca3":"vgb"},
{"name":"United States Virgin Islands","cca3":"vir"},
{"name":"Vietnam","cca3":"vnm"},
{"name":"Vanuatu","cca3":"vut"},
{"name":"Wallis and Futuna","cca3":"wlf"},
{"name":"Samoa","cca3":"wsm"},
{"name":"Yemen","cca3":"yem"},
{"name":"South Africa","cca3":"zaf"},
{"name":"Zambia","cca3":"zmb"},
{"name":"Zimbabwe","cca3":"zwe"}]
;

  public callback:any;
  constructor(public viewCtrl: ViewController, 
    private params: NavParams,
    public commonSrv:CommonService) {

    this.callback = this.params.get('cb');
    this.countries = CommonService.countries.response.payload.modules.get_countries;
    console.log("countrys successful", this.countries);

  }

  ionViewDidLoad() {
    // console.log('ionViewDidLoad CountryListPopPage');
  }

  countrySelected(country){
    if(this.callback) {
      this.callback(country);
    }
    this.viewCtrl.dismiss();

  }

}
